/*
  func Helper gen actionType
*/
export const asyncTypes = action => ({
  ORIGIN: action,
  HANDLER: `${action}_HANDLER`,
  PENDING: `${action}_PENDING`,
  START: `${action}_START`,
  MORE: `${action}_MORE`,
  SUCCESS: `${action}_SUCCESS`,
  FAILURE: `${action}_FAILURE`,
  ERROR: `${action}_ERROR`,
  CLEAR: `${action}_CLEAR`,
  END: `${action}_END`,
});

// Actions
/*
  OTHER functions
  Get App Version
  Upload Image
*/
export const OTHER = {
  OPEN_MENU: 'OPEN_MENU',
  GET_APP_VERSION: asyncTypes('OTHER/GET_APP_VERSION'),
  UPLOAD_IMAGE: asyncTypes('OTHER/UPLOAD_IMAGE'),
  SET_USER_DRAFT_INFO: asyncTypes('OTHER/SET_USER_DRAFT_INFO'),
  SET_DRIVER_DRAFT_INFO: asyncTypes('OTHER/SET_DRIVER_DRAFT_INFO'),
};

/*
  Check Connect Internet
*/
export const CONNECTIVITY = {
  APP_CONNECTIVITY_CHANGE: 'CONNECTIVITY/APP_CONNECTIVITY_CHANGE',
};

/*
  Loading
*/
export const LOADING = {
  FETCH: {
    FETCHING: 'LOADING/FETCH_FETCHING',
    NON_FETCHING: 'LOADING/FETCH_NON_FETCHING',
  },
  DIALOG: {
    SHOW: 'LOADING/DIALOG_SHOW',
    HIDE: 'LOADING/DIALOG_HIDE',
  },
};

export const ERROR = {
  DIALOG: {
    SHOW: 'ERROR/DIALOG_SHOW',
    HIDE: 'ERROR/DIALOG_HIDE',
  },
};

/*
  AUTH
  - login
  - logout
  - register
  - sendOTP
  - verify OTP
  - change Password
  - Reset Password
  - Change new Password
  - Update Profile
  - Register Vehicle
  - delete account
  - upgrade account personal to business
*/
export const AUTH = {
  SIGN_IN: asyncTypes('AUTH/SIGN_IN'),
  SIGN_OUT: asyncTypes('AUTH/SIGN_OUT'),
  SIGN_UP: asyncTypes('AUTH/SIGN_UP'),
  REFRESH_TOKEN: asyncTypes('AUTH/REFRESH_TOKEN'),
  ACCESS_TOKEN: asyncTypes('AUTH/ACCESS_TOKEN'),
  GET_USER_INFO: asyncTypes('AUTH/GET_USER_INFO'),
  UPDATE_PROFILE: asyncTypes('AUTH/UPDATE_PROFILE'),
  CHECK_OTP_SMS: asyncTypes('AUTH/CHECK_OTP_SMS'),
  CHECK_OTP_EMAIL: asyncTypes('AUTH/CHECK_OTP_EMAIL'),
  SEND_OTP_SMS: asyncTypes('AUTH/SEND_OTP_SMS'),
  SEND_OTP_EMAIL: asyncTypes('AUTH/SEND_OTP_EMAIL'),
  VERIFY_OTP_SMS: asyncTypes('AUTH/VERIFY_OTP_SMS'),
  VERIFY_OTP_EMAIL: asyncTypes('AUTH/VERIFY_OTP_EMAIL'),
  CHANGE_PASSWORD: asyncTypes('AUTH/CHANGE_PASSWORD'),
  CHECK_PHONE_OR_EMAIL_EXISTED: asyncTypes('AUTH/CHECK_PHONE_OR_EMAIL_EXISTED'),
  CHANGE_PHONE: asyncTypes('AUTH/CHANGE_PHONE'),
  CHANGE_EMAIL: asyncTypes('AUTH/CHANGE_EMAIL'),
  RESET_PASSWORD: asyncTypes('AUTH/RESET_PASSWORD'),
  DELETE_ACCOUNT: asyncTypes('AUTH/DELETE_ACCOUNT'),
  UPGRADE_ACCOUNT: asyncTypes('AUTH/UPGRADE_ACCOUNT'),
  UPDATE_PROCESS_STEP: asyncTypes('AUTH/UPDATE_PROCESS_STEP'),
  VALIDATION_LOG: asyncTypes('AUTH/VALIDATION_LOG'),
  CHANGE_STATUS_STOP_WORKING: asyncTypes('AUTH/CHANGE_STATUS_STOP_WORKING'),
  CHANGE_STATUS_REACTIVE: asyncTypes('AUTH/CHANGE_STATUS_REACTIVE'),
};

//SETTING
export const SETTING = {
  USER_PROFILE_SETTING: asyncTypes('SETTING/USER_PROFILE_SETTING'),
};

/*
PAYMENT BANK
  - Create Bank
  - Get List Bank
  - Get List Bank Setting
  - Delete Bank
  - Set Default Bank
  - Get Detail Bank Info
*/
export const PAYMENT = {
  CREATE_BANK: asyncTypes('PAYMENT/CREATE_BANK'),
  GET_LIST_BANK: asyncTypes('PAYMENT/GET_LIST_BANK'),
  GET_LIST_BANK_SETTING: asyncTypes('PAYMENT/GET_LIST_BANK_SETTING'),
  DELETE_BANK: asyncTypes('PAYMENT/DELETE_BANK'),
  SET_DEFAULT_BANK: asyncTypes('PAYMENT/SET_DEFAULT_BANK'),
  GET_DETAIL_BANK_INFO: asyncTypes('PAYMENT/GET_DETAIL_BANK_INFO'),
  CREATE_GATEWAY: asyncTypes('PAYMENT/CREATE_GATEWAY'),
  GET_LIST_GATEWAY: asyncTypes('PAYMENT/GET_LIST_GATEWAY'),
  GET_LIST_GATEWAY_SETTING: asyncTypes('PAYMENT/GET_LIST_GATEWAY_SETTING'),
  DELETE_GATEWAY: asyncTypes('PAYMENT/DELETE_GATEWAY'),
  SET_DEFAULT_GATEWAY: asyncTypes('PAYMENT/SET_DEFAULT_GATEWAY'),
  GET_DETAIL_GATEWAY_INFO: asyncTypes('PAYMENT/GET_DETAIL_GATEWAY_INFO'),
};

/*
USER PROFILE ATTRIBUTES
*/
export const USER_PROFILE_ATTRIBUTES = {
  USER_PROFILE_ATTRIBUTES: asyncTypes('USER_PROFILE_ATTRIBUTES/ATTRIBUTES'),
};

/*
ADDRESS(Địa chỉ)
- Get List Province (tỉnh, thành phố)
- Get List District (quận, huyện)
- Get List Ward (xã)
*/

export const ADDRESS = {
  GET_LIST_PROVINCE: asyncTypes('ADDRESS/GET_LIST_PROVINCE'),
  GET_LIST_DISTRICT: asyncTypes('ADDRESS/GET_LIST_DISTRICT'),
  GET_LIST_WARD: asyncTypes('ADDRESS/GET_LIST_WARD'),
  GET_ID_ADDRESS_GOOGLE: asyncTypes('ADDRESS/GET_ID_ADDRESS_GOOGLE'),
  GET_ADDRESS_FROM_GEOCODING_GOOGLE: asyncTypes(
    'ADDRESS/GET_ADDRESS_FROM_GEOCODING_GOOGLE',
  ),
};

/*
 * Sổ dịa chỉ
 * CRUID AddressBook
 * */

export const ADDRESS_BOOK = {
  GET_LIST_ADDRESS_BOOK: asyncTypes('ADDRESS_BOOK/GET_LIST_ADDRESS_BOOK'),
  GET_DETAIL_ADDRESS_BOOK: asyncTypes('ADDRESS_BOOK/GET_DETAIL_ADDRESS_BOOK'),
  CREATE_ADDRESS_BOOK: asyncTypes('ADDRESS_BOOK/CREATE_ADDRESS_BOOK'),
  UPDATE_ADDRESS_BOOK: asyncTypes('ADDRESS_BOOK/UPDATE_ADDRESS_BOOK'),
  DELETE_ADDRESS_BOOK: asyncTypes('ADDRESS_BOOK/DELETE_ADDRESS_BOOK'),
  SET_DEFAULT_ADDRESS_BOOK: asyncTypes('ADDRESS_BOOK/SET_DEFAULT_ADDRESS_BOOK'),
};

/*
 * TRIP
 * */

export const TRIP = {
  //Chi phi phat sinh
  // pending
  GET_LIST_COST_PENDING: asyncTypes('TRIP/GET_LIST_COST_PENDING'),
  // active
  GET_LIST_COST_ACTIVE: asyncTypes('TRIP/GET_LIST_COST_ACTIVE'),
  // Xem chi tiet chi phi phat sinh
  GET_DETAIL_COST: asyncTypes('TRIP/GET_DETAIL_COST'),
  // Them chi phi phat sinh
  COST_ACTION: asyncTypes('TRIP/COST_ACTION'),
  // Xoa chi phi phat sinh
  DELETE_COST_ACTION: asyncTypes('TRIP/DELETE_COST_ACTION'),
  // Sua chi phi phat sinh
  EDIT_COST_ACTION: asyncTypes('TRIP/EDIT_COST_ACTION'),
  //CONTINUE
  GET_LIST_TRIP_CONTINUE: asyncTypes('TRIP/GET_LIST_TRIP_CONTINUE'),
  GET_DETAIL_TRIP_CONTINUE: asyncTypes('TRIP/GET_DETAIL_TRIP_CONTINUE'),
  //UPDATE ASSIGNMENT STATUS TRIP
  UPDATE_TRIP_CONTINUE_ASSIGNMENT_STATUS: asyncTypes(
    'TRIP/UPDATE_TRIP_CONTINUE_ASSIGNMENT_STATUS',
  ),
  //UPDATE STATUS TRIP
  UPDATE_TRIP_CONTINUE_STATUS: asyncTypes('TRIP/UPDATE_TRIP_CONTINUE_STATUS'),

  //GONE
  GET_LIST_TRIP_GONE: asyncTypes('TRIP/GET_LIST_TRIP_GONE'),

  //RECALL
  GET_LIST_TRIP_RECALL: asyncTypes('TRIP/GET_LIST_TRIP_RECALL'),

  //REJECT
  GET_LIST_TRIP_REJECT: asyncTypes('TRIP/GET_LIST_TRIP_REJECT'),

  //SCHEDULE
  GET_SCHEDULE_OF_TRIPS: asyncTypes('TRIP/GET_SCHEDULE_OF_TRIPS'),

  //UPDATE ASSIGNMENT TRIP
  UPDATE_TRIP_ASSIGNMENT: asyncTypes('TRIP/UPDATE_TRIP_ASSIGNMENT'),
  //DETAILS_CURRENT_TRIP
  DETAILS_CURRENT_TRIP: asyncTypes('TRIP/DETAILS_CURRENT_TRIP'),
  //GPS_TRACKING_VEHICLE
  GPS_TRACKING_VEHICLE: asyncTypes('TRIP/GPS_TRACKING_VEHICLE'),
  //GET_LIST_TRIP_PROGRESS
  GET_LIST_TRIP_PROGRESS: asyncTypes('TRIP/GET_LIST_TRIP_PROGRESS'),
  UPDATE_TRIP_ASSIGNMENT_STATUS: asyncTypes(
    'TRIP/UPDATE_TRIP_ASSIGNMENT_STATUS',
  ),
  GET_SCHEDULE_JOURNEY: asyncTypes('TRIP/GET_SCHEDULE_JOURNEY'),

  //UPDATE ASSIGNMENT TRIP
  UPDATE_TRIP_STATUS: asyncTypes('TRIP/UPDATE_TRIP_STATUS'),
  CHECK_STATUS_ARRIVED: asyncTypes('TRIP/CHECK_STATUS_ARRIVED'),

  //UPDATE ASSIGNMENT TRIP
  TYPE_INPUT_DATA: asyncTypes('TRIP/TYPE_INPUT_DATA'),
  //schedule
  SCHEDULE_JOURNEY_OF_MONTH: asyncTypes('TRIP/SCHEDULE_JOURNEY_OF_MONTH'),
  SCHEDULE_JOURNEY_OF_DAY: asyncTypes('TRIP/SCHEDULE_JOURNEY_OF_DAY'),
  //bao su co
  REPORT_TROUBLE: asyncTypes('TRIP/REPORT_TROUBLE'),
};
