import {Dimensions, Platform, StatusBar} from 'react-native';
import {getSize} from 'utils/responsive';
export const deviceWidth = Dimensions.get('window').width;
export const deviceHeight = Dimensions.get('window').height;

export const BRANCH_NAME = 'driver';
//IPHONE X SIZE
export const IS_PHONE_X =
  Platform.OS === 'ios' && (deviceWidth === 812 || deviceHeight === 812);

export const StatusBarHeight = Platform.select({
  ios: IS_PHONE_X ? 44 : 20,
  android: StatusBar.currentHeight,
  default: 0,
});
export const paddingTopPlatform = paddingTop => paddingTop + StatusBarHeight;
export const REGEX_PHONE = /^(\+84-|\+84|0)[35789]\d{8}$/;
export const REGEX_NUMBER_PLATE =
  /^([1-9][0-9][A-Z][A-Z]?-([0-9][0-9][0-9])([0-9]|\.[0-9][0-9]))$/;
export const REGEX_LICENSE_CLASS = /^[0-9]{12}$/;
export const REGEX_COMPANY_TAX = /^([0-9]{10}(-[0-9]{3})?)$/;
export const REGEX_PERSONAL_ID = /^([0-9]{9}|[0-9]{12}|[A-Z][0-9]{7})$/;

export const getDateFuture = (countYearOrDate = 0) => {
  if (typeof countYearOrDate !== 'number') {
    return new Date(countYearOrDate);
  }
  return new Date(
    new Date().setFullYear(new Date().getFullYear() + countYearOrDate),
  );
};
//Color Constants
export const COLOR = {
  YELLOW_200: '#FFF6CC',
  COLOR_PRIMARY: '#2597A2',
  COLOR_PRIMARY_SECOND: '#2597A2',
  COLOR_PRIMARY_THIRD: '#378333',
  COLOR_PRIMARY_FOUR: '#1C6479',
  COLOR_PRIMARY_FIVE: '#5E81A0',
  COLOR_SECONDARY: '#fff',
  TEXT_CONTENT: '#27282A',
  TEXT_GREY: '#5F6167',
  TEXT_GREY_SECONDARY: '#76787F',
  COLOR_DISABLED: '#696969',
  COLOR_BACKGROUND: '#fff',
  COLOR_BACKGROUND_SECONDARY: '#ECEEED',
  COLOR_BACKGROUND_TEXT_INPUT: '#F3F5F6',
  COLOR_BACKGROUND_TEXT_INPUT_DISABLED: '#E6EBF0',
  COLOR_BORDER: '#DFE0E2',
  COLOR_TEXT_DISABLE: '#B9B9B9',
  COLOR_TEXT_INPUT: '#A0A1A7',
  COLOR_SUCCESS: '#48CFAE',
  COLOR_WARNING: '#F6BB43',
  COLOR_PENDING: '#FB6E52',
  COLOR_BOTTOM_TAB_ACTIVE: '#2E5B83',
  COLOR_BOTTOM_TAB: '#91A9BE',
  COLORS_BACKGROUND_BOTTOM_TAB: ['#001F3B', '#003768'],
  COLORS_HEADER_CONTAINER: ['#006D23', '#51B747'],
  COLORS_HEADER_CONTAINER_V2: [
    'rgba(29, 105, 125, 1)',
    'rgba(37, 151, 162, 1)',
  ],
  COLOR_BACKGROUND_GRAY: '#D2D2D2',
  COLOR_TEXT_TITLE_DRAWER: '#E6EBF0',
  COLOR_BACKGROUND_HEADER_DRAWER: '#001F3B',
  COLOR_BACKGROUND_SCREEN: '#F1F1F2',
  COLOR_TEXT_TITLE_INTRO: '#8A8D93',
  COLOR_GREEN_SUPPORT_700: '#00550C',
  COLOR_BORDER_TEXT_INPUT: '#B5B6BA',
  COLOR_DATE_TIME_INFO: '#4E5055',
  COLOR_CHECK_BOX: '#0059C8',
  COLOR_REQUIRED: '#FF0000',
  COLOR_BACKGROUND_SELECTED: '#CEECFF',
  LINEAR_WHITE_GREEN: ['#FFFFFF', 'rgba(234,251,233,0.82)'],
  LINEAR_GREEN_HELP: ['#1D697D', '#2597A2'],
  BORDER_FOCUS_TEXT_INPUT: '#98CBFF',
  GRAY: '#E5E5E5',
  WHITE: '#FFFFFF',
  GRAY2: '#e6e6e6',
  GRAY02: '#CACBCE',
  TEXT_BLUE_10: '#00192F',
  GRAY5: '#8A8D93',
  GRAY9: '#3B3C40',
  GRAY_LIGHT_5: '#F3F5F6',
  GREEN_LIGHT1: '#EDF8ED',
  GREEN_LIGHT2: '#B2E0B0',
  GREEN_2: '#D4EED3',
  GREEN_3: '#9CA7AC',
  GREEN_4: '#EDF8ED',
  GREEN_5: '#CDF3C6',
  BLUE_4: '#5E81A0',
  BLUE_7: '#003567',
  BLUE_DARK1: '#003567',
  BLUE_DARK2: '#003768',
  BLUE_SUPPORT_500: '#036FE3',
  BLUE_SUPPORT_100: '#E8F5FF',
  BLUE_SUPPORT_200: '#CEECFF',
  BLUE_SUPPORT_400: '#40A0FF',
  BLACK: '#000000',
  BUTTON_SET_DEFAULT: '#EDF8ED',
  COLOR_TEXT_POLICY: '#036FE3',
  COLOR_FLAT_LIST_SECONDARY: '#F3F5F6',
  COLOR_BACKGROUND_STATUS: '#EAF9E8',
  COLOR_BIG_TITLE: '#003567',
  TEXT_IMAGE_UPLOAD: '#4E5055',
  BACKGROUND_GRAY: '#E5E5E5',

  APP_HOT_LINE: ['#0EB05F', 'rgba(0, 171, 85, 0.53)'],
  //Toast
  TOAST_SUCCESS_BORDER: '#8FD28C',
  TOAST_SUCCESS_BACKGROUND: '#EDF8ED',
  TOAST_WARNING_BORDER: '#F07F23',
  TOAST_WARNING_BACKGROUND: '#FFF2E4',

  //ModalDialog
  POP_UP_SUCCESS: '#51B747',
  POP_UP_SUCCESS_BACKGROUND: '#EDF8ED',
  POP_UP_WARNING: '#B78300',
  POP_UP_TITLE: '#EAAF09',
  POP_UP_WARNING_BACKGROUND: '#FEF9DF',
  POP_UP_DANGER: '#DA294A',
  POP_UP_DANGER_BACKGROUND: '#FFF2F2',

  //Navigation
  TEXT_FOCUSED_TOP_TABBAR: '#003567',
  TEXT_TOP_TABBAR: '#5E81A0',
  BACKGROUND_TOP_TABBAR: '#CECECE',

  //Dashboard color
  DASH_BOARD_BACKGROUND: '#F3F5F7',
  MARK_LINEAR_GRADIENT: ['#88B1D6', '#1160AA', '#00509C'],

  //Status Color
  STATUS_SUCCESS_BORDER: '#5CCB53',
  STATUS_SUCCESS_BACKGROUND: '#EAF9E8',
  STATUS_SUCCESS_POINT: '#5CCB53',
  STATUS_SUCCESS_TEXT: '#51B747',
  STATUS_ERROR_BORDER: '#DA294A',
  STATUS_ERROR_BACKGROUND: '#FFF2F2',
  STATUS_ERROR_POINT: '#DA294A',
  STATUS_ERROR_TEXT: '#DA294A',
  STATUS_WARNING_BORDER: '#CC4500',
  STATUS_WARNING_BACKGROUND: '#FFF2E4',
  STATUS_WARNING_POINT: '#F07F23',
  STATUS_WARNING_TEXT: '#892300',
  STATUS_WAITING_BORDER: '#EAAF09',
  STATUS_WAITING_BACKGROUND: '#FEF9DF',
  STATUS_WAITING_POINT: '#FFC835',
  STATUS_WAITING_TEXT: '#7F5200',
  STATUS_DEFAULT_BORDER: '#0059C8',
  STATUS_DEFAULT_BACKGROUND: '#E8F5FF',
  STATUS_DEFAULT_POINT: '#40A0FF',
  STATUS_DEFAULT_TEXT: '#002A8E',
  STATUS_CLOSE_BORDER: '#76787F',
  STATUS_CLOSE_BACKGROUND: '#DFE0E2',
  STATUS_CLOSE_POINT: '#76787F',
  STATUS_CLOSE_TEXT: '#27282A',
  SEGMENT_ACTIVE: '#1B5E74',
  TRANSPARENT: 'transparent',
  RED_600: '#BD002A',
  RED_200: '#FFE0E0',
  GREEN_5: '#70A36A',
  ORANGE: '#E9A870',
  RED_1: '#D25B56',
  BLUE_8: '#2A4DD0',
  YELLOW_1: '#F7CD49',
  GRAY_10: '#9DA3AE',
  GRAY_11: '#AEC1CC',
};

export const LINEARGRADIENT = {
  PRIMARY: ['#1D697D', '#2597A2'],
  DISABLE: ['#585D63', '#A4A7AD'],
};

//CONSTANT SIZE PADDING
export const CONST_SIZE = {
  DEFAULT_PADDING_HORIZONTAL: getSize.m(16),
  DEFAULT_PADDING_VERTICAL: getSize.m(16),
  DEFAULT_PADDING_TOP: paddingTopPlatform(getSize.m(24)),
  ITEM_PADDING_VERTICAL: getSize.m(8),
  DEVICE_WIDTH: deviceWidth,
  DEVICE_HEIGHT: deviceHeight,
  BORDER_RADIUS: getSize.m(6),
  BORDER_RADIUS_BUTTON: getSize.m(4),
  BORDER_RADIUS_TEXT_INPUT: getSize.m(4),
};

// ICON_SIZE
export const ICON_SIZE = {
  SMALL: getSize.s(16),
  NORMAL: getSize.s(24),
  FIT: getSize.s(26),
  LARGE: getSize.s(30),
  X_LARGE: getSize.s(36),
};

export const SCENE_NAMES = {
  // Scene name
  VERIFY_PHONE: 'VERIFY_PHONE_SCREEN',
  GREETING: 'GREETING_SCREEN',
  SIGN_IN: 'SIGN_IN_SCREEN',
  SIGN_UP: 'SIGN_UP_SCREEN',
  SIGN_UP_FORM: 'SIGN_UP_FORM_SCREEN',
  HOME: 'HOME_SCREEN',
  MYJOURNEY_SCREEN: 'MYJOURNEY_SCREEN',
  ORDER_SCREEN: 'ORDER_SCREEN',
  DEBT_SCREEN: 'DEBT_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',
  SUPPORT_SCREEN: 'SUPPORT_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  DRAWER_NAVIGATION: 'DRAWER_NAVIGATION',
  ROOT_DRAWER_NAVIGATION: 'ROOT_DRAWER_NAVIGATION',
  SELECT_OTP: 'SELECT_OTP_SCREEN',
  VERIFY_OTP: 'VERIFY_OTP_SCREEN',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD_SCREEN',
  PAYMENT_SCREEN: 'PAYMENT_SCREEN',
  LICENSE_INFORMATION: 'LICENSE_INFORMATION',
  CHANGE_PHONE_OR_EMAIL: 'CHANGE_PHONE_OR_EMAIL_SCREEN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD_SCREEN',
  ANOTHER_INFORMATION: 'ANOTHER_INFO_SCREEN',
  PROVINCE: 'PROVINCE',
  DISTRICT: 'DISTRICT',
  WARDS: 'WARDS',
  SERVICES_PROVIDED: 'SERVICES_PROVIDED',
  TYPE_OF_GOODS: 'TYPE_OF_GOODS',
  NEW_PASSWORD_SCREEN: 'NEW_PASSWORD_SCREEN',
  DRIVER_INFORMATION: 'DRIVER_INFORMATION_SCREEN',
  DETAIL_DRIVER_INFO: 'DETAIL_DRIVER_INFO_SCREEN',
  LIST_PAYMENT_SETTING: 'LIST_PAYMENT_SETTING_SCREEN',
  DETAIL_BANK_INFO: 'DETAIL_BANK_INFO',
  DETAIL_GATEWAY_INFO: 'DETAIL_GATEWAY_INFO',
  LIST_BANK_SETTING: 'LIST_BANK_SETTING_SCREEN',
  LIST_GATEWAY_SETTING: 'LIST_GATEWAY_SETTING_SCREEN',
  VERIFY_OTP_CHANGE: 'VERIFY_OTP_CHANGE_SCREEN',
  ADDRESS: 'ADDRESS_SCREEN',
  DETAIL_ADDRESS: 'DETAIL_ADDRESS_SCREEN',
  CHANGE_LANGUAGE_SCREEN: 'CHANGE_LANGUAGE_SCREEN',
  LIST_QUOTE: 'LIST_QUOTE_SCREEN',
  CREATE_NEW_ORDER: 'CREATE_NEW_ORDER_SCREEN',
  MY_ORDER: 'MY_ORDER_SCREEN',
  REQUEST_QUOTE: 'REQUEST_QUOTE_SCREEN',
  DRIVER_INFO_START_SCREEN: 'DRIVER_INFO_START_SCREEN',

  DETAIL_TRIP: 'DETAIL_TRIP',
  DETAIL_SERVICE_TRANS: 'DETAIL_SERVICE_TRANS',
  DETAIL_TRIP_ROUTE_MAP: 'DETAIL_TRIP_ROUTE_MAP',
  DETAIL_TRIP_INPROGRESS: 'DETAIL_TRIP_INPROGRESS',
  COSTS_ADD: 'COSTS_ADD',
  ADD_COSTS_FORM_SCREEN: 'ADD_COSTS_FORM_SCREEN',
  TYPE_INPUT_DATA_TRIP: 'TYPE_INPUT_DATA_TRIP',
  TRIP_RECALL_SCREEN: 'TRIP_RECALL_SCREEN',
  TRIP_REFUSE_SCREEN: 'TRIP_REFUSE_SCREEN',
  TRIP_SCHEDULE_SCREEN: 'TRIP_SCHEDULE_SCREEN',
  DETAIL_COSTS: 'DETAIL_COSTS',

  REPORT_TROUBLE_TRIP_SCREEN: 'REPORT_TROUBLE_TRIP_SCREEN',
  MAP_DIRECTION: 'MAP_DIRECTION',
  MAP_SCREEN: 'MAP_SCREEN',
};

//hot key
export const HOT_KEY = {
  SUCCESS: 'Success',
};

export const HOT_LINE = {
  PHONE: '1900 88 88 00',
};
// check format date DD/MM/YYYY
export const REGEX_DATE_SHORT =
  /^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[1,3-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{4})$/gm;
//Type
export const ACCOUNT_TYPE = {
  COMPANY: 'company',
  PERSONAL: 'personal',
};

export const ACCOUNT_STATUS = {
  UNFINISHED: 'unfinished',
  DRAFT: 'draft',
  WORKING: 'working',
  STOP_WORKING: 'stop_working',
  PENDING_APPROVAL: 'pending_approval',
  NEED_UPDATE: 'need_update',
  LOADING: 'loading',
  LOCKED: 'locked',
  CLOSED: 'closed',
  EXPIRED: 'expired',
  PENDING_UPGRADE_REVIEW: 'pending_upgrade_review',
};

export const GPS_STATUS = {
  CONNECTED: 'connected',
  UNCONNECTED: 'unconnected',
};

export const MODAL_BOX_OPTIONS = {
  INACTIVE: 'inactive',
  ACTIVE: 'active',
  LOCK: 'lock',
  DELETE: 'delete',
  CONVERT_FUNCTIONS: 'convert_functions',
};

export const DEFAULT_AVATAR_IMAGE =
  'https://www.w3schools.com/howto/img_avatar.png';

export const KEY_ACTION_OTP = {
  CHANGE_PHONE_OR_EMAIL: 'change_phone_or_email',
  LOGIN: 'login',
  RESET_PASSWORD: 'reset_password',
};

//enumStep
export const PROCESS_STEPS = {
  FILLING_LOGIN_INFORMATION: 'filling_login_information',
  FILLING_COMPANY_INFORMATION: 'filling_company_information',
  FILLING_DRIVER_INFORMATION: 'filling_driver_information',
  FINISHING: 'finishing',
};

export const KEY_ACTION_PROFILE = {
  UPDATE_AFTER_COMPLETED: 'update_after_completed',
  UPDATE_DRAFT_DATA: 'update_draft_data',
  NEXT_STEP: 'next_step',
  CREATE_DRIVER_AFTER_COMPLETED: 'create_driver_after_completed',
  GET_USER_INFOR_AFTER_UPDATE: 'get_user_infor_after_update',
  CHANGE_TYPE_COMPANY_INFORMATION: 'change_type_company_information',
  CHANGE_TYPE_COMPANY_STEP: 'change_type_company_step',
  GET_DRIVER_INFORMATION: 'get_driver_information',
  GET_DRIVER_INFORMATION_DETAIL: 'get_driver_information_detail',
  REFRESH_HOME_PAGE: 'refresh_home_page',
  FINISHING_STEP: 'finishing_step',
};

export const GG_API_KEY = 'AIzaSyCt-9twVYLiCvdNA4Pitak8Ik9L3maZT_4';
export const GOOGLE_PLACES_API_KEY = 'AIzaSyAn39BT0DBBF2KH4Fmom0eRCBaLcsYy2KA';
//enumStep
export const JOURNEY_ROUTE_STATUS = {
  // lộ trình đang đi
  BEING_TRANSPORTED: 'journey_route_processing',
  // lộ trình đã nhận lệnh
  ACCEPTED: 'journey_route_accepted',
  // lộ trình đã đến
  DONE: 'journey_route_done',
};

export const DEFAULT_LOCATION_MAP = {
  latitude: 10.796704879554877,
  latitudeDelta: 0.02215115137855861,
  longitude: 106.67637186124921,
  longitudeDelta: 0.011000074446172903,
};
