import { SVG_NAME } from 'assets/path';
import { useIconResizeHOC } from 'hooks/useIconSvgResizeHOC';

const AppIcons = {
    //sign up
    ENTERPRISE: useIconResizeHOC(SVG_NAME.ENTERPRISE, { s: 45 }),
    PERSON: useIconResizeHOC(SVG_NAME.PERSON, { s: 46 }),
    //notification
    NOTIFICATION_ICON: useIconResizeHOC(SVG_NAME.NOTIFICATION_ICON, { s: 24 }),
    CLOUDDOWNLOAD_ICON: useIconResizeHOC(SVG_NAME.CLOUDDOWNLOAD_ICON, { s: 44 }),
    LARGENOTIFICATION_ICON: useIconResizeHOC(SVG_NAME.LARGENOTIFICATION_ICON, { w: 172, h: 166 }),
    CLOUD: useIconResizeHOC(SVG_NAME.CLOUD, { w: 201, h: 148 }),
    //common
    CREATE_ORDER: useIconResizeHOC(SVG_NAME.CREATE_ORDER, {s: 48}),
    LIST_QUOTE: useIconResizeHOC(SVG_NAME.LIST_QUOTE, { w: 80, h: 81 }),
    TRASH_CIRCLE: useIconResizeHOC(SVG_NAME.TRASH_CIRCLE, { s: 32 }),
    CHECK_CIRCLE: useIconResizeHOC(SVG_NAME.CHECK_CIRCLE, { s: 32 }),
    MAP_CIRCLE: useIconResizeHOC(SVG_NAME.MAP_CIRCLE, { s: 40 }),
    BACK_ICON: useIconResizeHOC(SVG_NAME.BACK_ICON, { s: 24 }),
    EYE_OFF_OUTLINE: useIconResizeHOC(SVG_NAME.EYE_OFF_OUTLINE, { s: 24 }),
    EYE_OUTLINE: useIconResizeHOC(SVG_NAME.EYE_OUTLINE, { s: 24 }),
    LOGO_COLOR: useIconResizeHOC(SVG_NAME.LOGO_COLOR, { w: 127, h: 112 }),
    LOGO_WHITE: useIconResizeHOC(SVG_NAME.LOGO_WHITE, { w: 112, h: 100 }),
    GLOBAL: useIconResizeHOC(SVG_NAME.GLOBAL, { s: 18 }),
    HOTLINE_RIGHT: useIconResizeHOC(SVG_NAME.HOTLINE_RIGHT, { w: 34, h: 41 }),
    HOTLINE_LEFT: useIconResizeHOC(SVG_NAME.HOTLINE_LEFT, { s: 41 }),
    HELP: useIconResizeHOC(SVG_NAME.HELP, { w: 32, h: 33 }),
    LOGOUT: useIconResizeHOC(SVG_NAME.LOGOUT, { w: 32, h: 33 }),
    ADD: useIconResizeHOC(SVG_NAME.ADD, { s: 32 }),
    FILTER: useIconResizeHOC(SVG_NAME.FILTER, { s: 36 }),
    FILTER_GREEN: useIconResizeHOC(SVG_NAME.FILTER_GREEN, { s: 40 }),
    FILTER_BLUE: useIconResizeHOC(SVG_NAME.FILTER_BLUE, { s: 40 }),
    DOWN: useIconResizeHOC(SVG_NAME.DOWN, { s: 24 }),
    RIGHT: useIconResizeHOC(SVG_NAME.RIGHT, { s: 24 }),
    SEARCH: useIconResizeHOC(SVG_NAME.SEARCH, { s: 24 }),
    CLOCK: useIconResizeHOC(SVG_NAME.CLOCK, { s: 11 }),
    PHONE: useIconResizeHOC(SVG_NAME.PHONE, { s: 24 }),
    DRIVER_LICENSE: useIconResizeHOC(SVG_NAME.DRIVER_LICENSE, { w: 43, h: 28 }),
    LICENSE: useIconResizeHOC(SVG_NAME.LICENSE, { w: 44, h: 30  }),
    CLOSE_ICON: useIconResizeHOC(SVG_NAME.CLOSE_ICON, { w: 24, h: 252  }),
    PLUS: useIconResizeHOC(SVG_NAME.PLUS, { s: 36 }),
    PLUS_GREEN: useIconResizeHOC(SVG_NAME.PLUS_GREEN, { s: 32 }),
    DOT: useIconResizeHOC(SVG_NAME.DOT, { s: 32 }),
    EDIT: useIconResizeHOC(SVG_NAME.EDIT, { s: 36 }),
    ICON_LOGO: useIconResizeHOC(SVG_NAME.ICON_LOGO, { w: 64, h: 56  }),
    SEARCH_HEADER: useIconResizeHOC(SVG_NAME.SEARCH_HEADER, { s: 36 }),
    CALENDAR: useIconResizeHOC(SVG_NAME.CALENDAR, { s: 24 }),
    CAMERA: useIconResizeHOC(SVG_NAME.CAMERA, { w: 24, h: 25  }),
    TRUCK: useIconResizeHOC(SVG_NAME.TRUCK, { s: 24 }),
    WEIGHT: useIconResizeHOC(SVG_NAME.WEIGHT, { s: 24 }),
    GPS: useIconResizeHOC(SVG_NAME.GPS, { s: 16 }),
    MENU: useIconResizeHOC(SVG_NAME.MENU, { s: 24 }),
    TRASH_ICON: useIconResizeHOC(SVG_NAME.TRASH_ICON, { s: 36 }),
    CANCEL: useIconResizeHOC(SVG_NAME.CANCEL, { s: 20 }),
    GO_BACK: useIconResizeHOC(SVG_NAME.GO_BACK, { w: 28, h: 24  }),
    ADD_BANK: useIconResizeHOC(SVG_NAME.ADD_BANK, { s: 36 }),
    ROMOOC: useIconResizeHOC(SVG_NAME.ROMOOC, { s: 20 }),
    DOT_GRAY: useIconResizeHOC(SVG_NAME.DOT_GRAY, { s: 24 }),
    CONTAINER: useIconResizeHOC(SVG_NAME.CONTAINER, { s: 24 }),
    STRUCK_NAVIGATE: useIconResizeHOC(SVG_NAME.STRUCK_NAVIGATE, { w: 17, h: 16  }),
    STRUCK_NAVIGATE_GRAY: useIconResizeHOC(SVG_NAME.STRUCK_NAVIGATE_GRAY, { s: 21 }),
    GPS_BULE: useIconResizeHOC(SVG_NAME.GPS_BULE, { s: 21 }),
    GPS_GRAY: useIconResizeHOC(SVG_NAME.GPS_GRAY, { s: 21 }),
    UP_BLUE: useIconResizeHOC(SVG_NAME.UP_BLUE, { s: 21 }),
    CAMERA_UPLOAD: useIconResizeHOC(SVG_NAME.CAMERA_UPLOAD, { s: 21 }),
    PIN_DROP: useIconResizeHOC(SVG_NAME.PIN_DROP, { s: 21 }),
    CREDIT_CARD: useIconResizeHOC(SVG_NAME.CREDIT_CARD, { s: 21 }),
    STAR: useIconResizeHOC(SVG_NAME.STAR, { s: 21 }),
    STAR_FILL: useIconResizeHOC(SVG_NAME.STAR_FILL, { s: 21 }),
    CHECK: useIconResizeHOC(SVG_NAME.CHECK, { s: 21 }),
    BANK_CARD: useIconResizeHOC(SVG_NAME.BANK_CARD, { s: 21 }),
    MINUS: useIconResizeHOC(SVG_NAME.MINUS, { s: 21 }),
    PLUS_COUNTER: useIconResizeHOC(SVG_NAME.PLUS_COUNTER, { s: 21 }),
    LOCATION: useIconResizeHOC(SVG_NAME.LOCATION, { s: 21 }),
    INFO: useIconResizeHOC(SVG_NAME.INFO, { s: 21 }),
    SORT: useIconResizeHOC(SVG_NAME.SORT, { s: 21 }),
    TOP: useIconResizeHOC(SVG_NAME.TOP, { s: 21 }),
    CHECKED_BOX: useIconResizeHOC(SVG_NAME.CHECKED_BOX, { s: 21 }),
    AVATAR_ICON: useIconResizeHOC(SVG_NAME.AVATAR_ICON, { s: 21 }),
    AVATAR_ICON_BLUE: useIconResizeHOC(SVG_NAME.AVATAR_ICON_BLUE, { s: 21 }),
    SHIELD: useIconResizeHOC(SVG_NAME.SHIELD, { s: 21 }),
    CLOCKED_PASS: useIconResizeHOC(SVG_NAME.CLOCKED_PASS, { s: 21 }),
    CONTACT: useIconResizeHOC(SVG_NAME.CONTACT, { s: 21 }),
    PIN: useIconResizeHOC(SVG_NAME.PIN, { s: 21 }),
    CHEVRON_RIGHT: useIconResizeHOC(SVG_NAME.CHEVRON_RIGHT, { s: 21 }),
    ADD_GRAY: useIconResizeHOC(SVG_NAME.ADD_GRAY, { s: 21 }),
    POP_UP_SUCCESS: useIconResizeHOC(SVG_NAME.POP_UP_SUCCESS, { s: 21 }),
    DOT_ORANGE: useIconResizeHOC(SVG_NAME.DOT_ORANGE, { s: 21 }),
    PHONE_SMALL: useIconResizeHOC(SVG_NAME.PHONE_SMALL, { s: 21 }),
    LINE: useIconResizeHOC(SVG_NAME.LINE, { s: 21 }),
    CHECK_SELECTED: useIconResizeHOC(SVG_NAME.CHECK_SELECTED, { s: 21 }),
    RANK_START: useIconResizeHOC(SVG_NAME.RANK_START, { s: 21 }),
    UP_GREEN: useIconResizeHOC(SVG_NAME.UP_GREEN, { s: 21 }),
    DOWN_GREEN: useIconResizeHOC(SVG_NAME.DOWN_GREEN, { s: 21 }),
    CAMERA_AVATAR: useIconResizeHOC(SVG_NAME.CAMERA_AVATAR, { s: 21 }),
    RESET_PASSWORD_LOCK: useIconResizeHOC(SVG_NAME.RESET_PASSWORD_LOCK, { s: 21 }),
    CHECK_NOTE_PASSWORD: useIconResizeHOC(SVG_NAME.CHECK_NOTE_PASSWORD, { s: 21 }),
    //Toast
    TICK_SQUARE: useIconResizeHOC(SVG_NAME.TICK_SQUARE, { s: 21 }),
    CANCEL_GRAY: useIconResizeHOC(SVG_NAME.CANCEL_GRAY, { s: 21 }),
    INFO_CIRCLE: useIconResizeHOC(SVG_NAME.INFO_CIRCLE, { s: 21 }),

    //bottom navigation
    HOME_BOTTOM_NAV_ACTIVE: useIconResizeHOC(SVG_NAME.HOME_BOTTOM_NAV_ACTIVE, { s: 21 }),
    HOME_BOTTOM_NAV_INACTIVE: useIconResizeHOC(SVG_NAME.HOME_BOTTOM_NAV_INACTIVE, { s: 21 }),
    USER_BOTTOM_NAV_ACTIVE: useIconResizeHOC(SVG_NAME.USER_BOTTOM_NAV_ACTIVE, { s: 21 }),
    USER_BOTTOM_NAV_INACTIVE: useIconResizeHOC(SVG_NAME.USER_BOTTOM_NAV_INACTIVE, { s: 21 }),
    ORDER_BOTTOM_NAV_ACTIVE: useIconResizeHOC(SVG_NAME.ORDER_BOTTOM_NAV_ACTIVE, { s: 21 }),
    ORDER_BOTTOM_NAV_INACTIVE: useIconResizeHOC(SVG_NAME.ORDER_BOTTOM_NAV_INACTIVE, { s: 21 }),
    DEBT_BOTTOM_NAV_ACTIVE: useIconResizeHOC(SVG_NAME.DEBT_BOTTOM_NAV_ACTIVE, { s: 21 }),
    DEBT_BOTTOM_NAV_INACTIVE: useIconResizeHOC(SVG_NAME.DEBT_BOTTOM_NAV_INACTIVE, { s: 21 }),
    MENU_BOTTOM_NAV_ACTIVE: useIconResizeHOC(SVG_NAME.MENU_BOTTOM_NAV_ACTIVE, { s: 21 }),
    MENU_BOTTOM_NAV_INACTIVE: useIconResizeHOC(SVG_NAME.MENU_BOTTOM_NAV_INACTIVE, { s: 21 }),

    //drawer navigation
    SENDER_BACKGROUND_DRAWER: useIconResizeHOC(SVG_NAME.SENDER_BACKGROUND_DRAWER, { s: 21 }),
    MESSENGER_ICON_DRAWER: useIconResizeHOC(SVG_NAME.MESSENGER_ICON_DRAWER, { s: 21 }),
    ZALO_ICON_DRAWER: useIconResizeHOC(SVG_NAME.ZALO_ICON_DRAWER, { s: 21 }),
    GLOBAL_ICON_DRAWER: useIconResizeHOC(SVG_NAME.GLOBAL_ICON_DRAWER, { s: 21 }),
    BACK_ICON_DRAWER: useIconResizeHOC(SVG_NAME.BACK_ICON_DRAWER, { s: 21 }),
    AVATAR: useIconResizeHOC(SVG_NAME.AVATAR, { s: 21 }),
    RACING: useIconResizeHOC(SVG_NAME.RACING, { s: 21 }),
    SETTING_DRAWER: useIconResizeHOC(SVG_NAME.SETTING_DRAWER, { s: 21 }),

    //MODALBOX
    LOCK: useIconResizeHOC(SVG_NAME.LOCK, { s: 21 }),
    MINUS_CIRCLE: useIconResizeHOC(SVG_NAME.MINUS_CIRCLE, { s: 21 }),
    TRASH: useIconResizeHOC(SVG_NAME.TRASH, { s: 21 }),
    TRASH_ERROR: useIconResizeHOC(SVG_NAME.TRASH_ERROR, { s: 21 }),
    PERSONAL_TO_COMPANY: useIconResizeHOC(SVG_NAME.PERSONAL_TO_COMPANY, { s: 21 }),
    // Step owner start
    STEP1: useIconResizeHOC(SVG_NAME.STEP1, { s: 21 }),
    STEP2_PROCESS: useIconResizeHOC(SVG_NAME.STEP2_PROCESS, { s: 21 }),
    STEP2_COMPLETE: useIconResizeHOC(SVG_NAME.STEP2_COMPLETE, { s: 21 }),
    STEP3_DISABLE: useIconResizeHOC(SVG_NAME.STEP3_DISABLE, { s: 21 }),
    STEP3_PROCESS: useIconResizeHOC(SVG_NAME.STEP3_PROCESS, { s: 21 }),
    STEP3_COMPLETE: useIconResizeHOC(SVG_NAME.STEP3_COMPLETE, { s: 21 }),
    STEP4DISABLE: useIconResizeHOC(SVG_NAME.STEP4DISABLE, { s: 21 }),
    STEP4: useIconResizeHOC(SVG_NAME.STEP4, { s: 21 }),
    // owner start screen
    OWNER_COMPLETE_START_BANNER: useIconResizeHOC(SVG_NAME.OWNER_COMPLETE_START_BANNER, { s: 21 }),
    ARROW_RIGHT_CIRCLE: useIconResizeHOC(SVG_NAME.ARROW_RIGHT_CIRCLE, { s: 21 }),
    TRUCK_CIRCLE: useIconResizeHOC(SVG_NAME.TRUCK_CIRCLE, { s: 21 }),
    CONTAINER_CIRCLE: useIconResizeHOC(SVG_NAME.CONTAINER_CIRCLE, { s: 21 }),
    TRASH_OPTION: useIconResizeHOC(SVG_NAME.TRASH_OPTION, { s: 21 }),
    LOCK_OPTION: useIconResizeHOC(SVG_NAME.LOCK_OPTION, { s: 21 }),
    MINUS_CIRCLE_OPTION: useIconResizeHOC(SVG_NAME.MINUS_CIRCLE_OPTION, { s: 21 }),
    REFRESH_OPTION: useIconResizeHOC(SVG_NAME.REFRESH_OPTION, { s: 21 }),
    //dashBoard
    MY_ORDER: useIconResizeHOC(SVG_NAME.MY_ORDER, { w: 80, h: 81 }),
    APPROVED_ROUTE: useIconResizeHOC(SVG_NAME.APPROVED_ROUTE, { s: 21 }),
    REQUEST_QUOTE: useIconResizeHOC(SVG_NAME.REQUEST_QUOTE, { w: 81, h: 80 }),
    HEAD_PHONE: useIconResizeHOC(SVG_NAME.HEAD_PHONE, { w: 29, h: 24 }),
    HELP_RIGHT: useIconResizeHOC(SVG_NAME.HELP_RIGHT, { w: 68, h: 43 }),
    CAR_OWNER_INFO: useIconResizeHOC(SVG_NAME.CAR_OWNER_INFO, { s: 76}),
    VEHICLE_LIST: useIconResizeHOC(SVG_NAME.VEHICLE_LIST, { s: 80 }),
    DRIVER_LIST: useIconResizeHOC(SVG_NAME.DRIVER_LIST, { s: 80 }),
    PAYMENT_INFO: useIconResizeHOC(SVG_NAME.PAYMENT_INFO, { s: 80 }),
    OTHER_INFO: useIconResizeHOC(SVG_NAME.OTHER_INFO, { s: 80 }),
    ACCOUNT_INFO: useIconResizeHOC(SVG_NAME.ACCOUNT_INFO, { w: 58, h: 60 }),
    ELLIPSE: useIconResizeHOC(SVG_NAME.ELLIPSE, { w: 293, h: 301 }),
    PHONE_HOTLINE: useIconResizeHOC(SVG_NAME.PHONE_HOTLINE, { s: 32 }),
    ZALO: useIconResizeHOC(SVG_NAME.ZALO, { s: 32 }),
    MESSENGER: useIconResizeHOC(SVG_NAME.MESSENGER, { s: 32 }),

    MYJOURNEY: useIconResizeHOC(SVG_NAME.MYJOURNEY, { s: 76}),
    INFOR_ACCOUNT: useIconResizeHOC(SVG_NAME.INFOR_ACCOUNT, { s: 76}),
    OTHER_SETTING: useIconResizeHOC(SVG_NAME.OTHER_SETTING, { s: 76}),



    //userInformation
    USER: useIconResizeHOC(SVG_NAME.USER, { s: 21 }),
    USER_PHONE: useIconResizeHOC(SVG_NAME.USER_PHONE, { s: 21 }),
    USER_MAIL: useIconResizeHOC(SVG_NAME.USER_MAIL, { s: 21 }),
    USER_RESET: useIconResizeHOC(SVG_NAME.USER_RESET, { s: 21 }),
    USER_RIGHT: useIconResizeHOC(SVG_NAME.USER_RIGHT, { s: 21 }),

    //Language
    FLAG_VN: useIconResizeHOC(SVG_NAME.FLAG_VN, { s: 21 }),
    FLAG_EN: useIconResizeHOC(SVG_NAME.FLAG_EN, { s: 21 }),
}

export default AppIcons;
